#define deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-app-deployment
  labels:
    app: service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-app
  template:
    metadata:
      labels:
        app: service-app
    spec:
      containers:
      - name: service-app
        image: goyalsweta/service-app:1.0
        ports:
        - containerPort: 8080

---

#define service
apiVersion: v1
kind: Service
metadata:
  name: service-app-service
spec:
  type: NodePort
  selector:
    app: service-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30020
